### ISSUE TITLE
UR23 / RPI5 issue

### ISSUE THREAD

**Issue by ericct** [mdsimon2/RPi-CamillaDSP#1]
Hello,

More a question than an issue: you're mentioning that UR23 is NOT compatible with RPI5. Is it still the case? What is the reason (I cannot find the information on the Web). 

Thanks!

**Comment by mdsimon2** [comment]
Yes, that is still the case. See here for more info -> https://www.diyaudio.com/community/threads/hifime-ur23-usb-product-id-pi5.419881/.

Michael
